
/**
* ClientsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Client.idl
* pi�tek, 4 czerwca 2021 18:53:24 CEST
*/

public interface ClientsOperations 
{
  String firstName ();
  void firstName (String newFirstName);
  String lastName ();
  void lastName (String newLastName);
  String companyName ();
  void companyName (String newCompanyName);
  boolean contractActive ();
  void contractActive (boolean newContractActive);
  Long PESEL ();
  void PESEL (int newPESEL);
  ClientsPackage.Client client ();
  void client (ClientsPackage.Client newClient);
  ClientsPackage.Client[] clients ();
  void clients (ClientsPackage.Client[] newClients);
  ClientsPackage.Client setPesel ();
  ClientsPackage.Client updateClient ();
} // interface ClientsOperations
