
/**
* Clients.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Client.idl
* pi¹tek, 4 czerwca 2021 18:53:24 CEST
*/

public interface Clients extends ClientsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Clients
