
/**
* ClientsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Client.idl
* pi¹tek, 4 czerwca 2021 18:53:24 CEST
*/

public final class ClientsHolder implements org.omg.CORBA.portable.Streamable
{
  public Clients value = null;

  public ClientsHolder ()
  {
  }

  public ClientsHolder (Clients initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientsHelper.type ();
  }

}
