package ClientsPackage;


/**
* ClientsPackage/ClientSequenceHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Client.idl
* pi¹tek, 4 czerwca 2021 18:53:24 CEST
*/

abstract public class ClientSequenceHelper
{
  private static String  _id = "IDL:Clients/ClientSequence:1.0";

  public static void insert (org.omg.CORBA.Any a, ClientsPackage.Client[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ClientsPackage.Client[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = ClientsPackage.ClientHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (ClientsPackage.ClientSequenceHelper.id (), "ClientSequence", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ClientsPackage.Client[] read (org.omg.CORBA.portable.InputStream istream)
  {
    ClientsPackage.Client value[] = null;
    int _len0 = istream.read_long ();
    value = new ClientsPackage.Client[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = ClientsPackage.ClientHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ClientsPackage.Client[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      ClientsPackage.ClientHelper.write (ostream, value[_i0]);
  }

}
