package ClientsPackage;


/**
* ClientsPackage/ClientHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Client.idl
* pi¹tek, 4 czerwca 2021 18:53:24 CEST
*/

abstract public class ClientHelper
{
  private static String  _id = "IDL:Clients/Client:1.0";

  public static void insert (org.omg.CORBA.Any a, ClientsPackage.Client that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ClientsPackage.Client extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [5];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "firstName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "lastName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_boolean);
          _members0[2] = new org.omg.CORBA.StructMember (
            "contractActive",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[3] = new org.omg.CORBA.StructMember (
            "companyName",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_long);
          _members0[4] = new org.omg.CORBA.StructMember (
            "PESEL",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (ClientsPackage.ClientHelper.id (), "Client", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ClientsPackage.Client read (org.omg.CORBA.portable.InputStream istream)
  {
    ClientsPackage.Client value = new ClientsPackage.Client ();
    value.firstName = istream.read_string ();
    value.lastName = istream.read_string ();
    value.contractActive = istream.read_boolean ();
    value.companyName = istream.read_string ();
    value.PESEL = istream.read_long ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ClientsPackage.Client value)
  {
    ostream.write_string (value.firstName);
    ostream.write_string (value.lastName);
    ostream.write_boolean (value.contractActive);
    ostream.write_string (value.companyName);
    ostream.write_long (value.PESEL);
  }

}
