package ClientsPackage;

/**
* ClientsPackage/ClientHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Client.idl
* pi¹tek, 4 czerwca 2021 18:53:24 CEST
*/

public final class ClientHolder implements org.omg.CORBA.portable.Streamable
{
  public ClientsPackage.Client value = null;

  public ClientHolder ()
  {
  }

  public ClientHolder (ClientsPackage.Client initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ClientsPackage.ClientHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ClientsPackage.ClientHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ClientsPackage.ClientHelper.type ();
  }

}
