package ClientsPackage;


/**
* ClientsPackage/Client.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Client.idl
* pi¹tek, 4 czerwca 2021 18:53:24 CEST
*/

public final class Client implements org.omg.CORBA.portable.IDLEntity
{
  public String firstName = null;
  public String lastName = null;
  public boolean contractActive = false;
  public String companyName = null;
  public int PESEL = (int)0;

  public Client ()
  {
  } // ctor

  public Client (String _firstName, String _lastName, boolean _contractActive, String _companyName, int _PESEL)
  {
    firstName = _firstName;
    lastName = _lastName;
    contractActive = _contractActive;
    companyName = _companyName;
    PESEL = _PESEL;
  } // ctor

} // class Client
